######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 25 12:07:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=network

# Input
HEADERS += cacamap.h
SOURCES += cacamap.cpp main.cpp
