######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 15 16:18:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT+= network

# Input
HEADERS += cacamap.h
SOURCES += cacamap.cpp main.cpp
